FROM ghcr.io/astral-sh/uv:python3.10-bookworm AS base

# install gcloud to make it easier to access cloud storage
ARG install_gcloud=y
RUN if [ "${install_gcloud}" = "y" ]; then \
      mkdir -p /usr/local/gcloud \
      && curl -q https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz \
        -o /tmp/google-cloud-sdk.tar.gz \
      && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
      && rm /tmp/google-cloud-sdk.tar.gz \
      && /usr/local/gcloud/google-cloud-sdk/install.sh --usage-reporting false; \
    fi
ENV PATH /usr/local/gcloud/google-cloud-sdk/bin:$PATH

ARG install_docker
RUN if [ "${install_docker}" = "y" ]; then curl -sSL https://get.docker.com/ | sh; fi

ENV PATH /root/.local/bin:$PATH

WORKDIR /opt/sciencebeam-grobid-trainer-tools

ENV VENV=/opt/venv
ENV VIRTUAL_ENV=${VENV} PYTHONUSERBASE=${VENV} PATH=${VENV}/bin:$PATH

RUN uv venv "${VENV}"

COPY pyproject.toml uv.lock ./
RUN uv sync --active --frozen

COPY sciencebeam_trainer_grobid_tools ./sciencebeam_trainer_grobid_tools
COPY config ./config
RUN uv pip install -e .

COPY docker ./docker
COPY scripts /opt/scripts
ENV PATH /opt/scripts:$PATH

# tools-dev
FROM base AS tools-dev

RUN uv sync --active --frozen --dev

COPY tests ./tests

COPY .flake8 .pylintrc ./


# tools
FROM base AS tools

ARG revision
LABEL org.opencontainers.image.revision="${revision}"
LABEL org.opencontainers.image.source=https://github.com/elifesciences/sciencebeam-trainer-grobid-tools
